apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-deploy
  labels:
    name: postgres-deploy
    app: FGT
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: FGT
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: FGT
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: "POSTGRES_USER"
              value: "postgres2"
            - name: "POSTGRES_PASSWORD"
              value: "password" 
            - name: "POSTGRES_DB"
              value: "financetracker"
          volumeMounts:
            - name: pv-data-fgt
              mountPath: /var/lib/postgresql/fgtdata
      volumes:
        - name: pv-data-fgt
          persistentVolumeClaim:
            claimName: pvc-fgt
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  labels:
    name: frontend-deploy
    app: FGT
spec:
  replicas: 2
  selector:
    matchLabels:
      name: frontend-pod
      app: FGT
  template:
    metadata:
      name: frontend-pod
      labels:
        name: frontend-pod
        app: FGT
    spec:
      containers:
        - name: frontend
          image: akhilzemoso/fe_fgt_jenkins:18fb6fd3395ad74a99e0dc530712e1c298e57e73
          ports:
            - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-budget-deploy
  labels:
    name: backend-budget-deploy
    app: FGT
spec:
  replicas: 2
  selector:
    matchLabels:
      name: backend-budget-pod
      app: FGT
  template:
    metadata:
      name: backend-budget-pod
      labels:
        name: backend-budget-pod
        app: FGT
    spec:
      containers:
        - name: backend
          image: akhilzemoso/be_budget_jenkins:c52c3265c55268a872faa7f793666cf416749be1
          ports:
            - containerPort: 8083
          env:
            - name: "SPRING_DATASOURCE_URL"
              value: "jdbc:postgresql://postgres:5432/financetracker"
            - name: "SPRING_DATASOURCE_USERNAME"
              value: "postgres2"
            - name: "SPRING_DATASOURCE_PASSWORD"
              value: "password"
            - name: "SPRING_JPA_HIBERNATE_DDL_AUTO"
              value: "update"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-transaction-deploy
  labels:
    name: backend-transaction-deploy
    app: FGT
spec:
  replicas: 2
  selector:
    matchLabels:
      name: backend-transaction-pod
      app: FGT
  template:
    metadata:
      name: backend-transaction-pod
      labels:
        name: backend-transaction-pod
        app: FGT
    spec:
      containers:
        - name: backend
          image: akhilzemoso/be_transaction_jenkins:26d206e169d097b8d0d42230e1f6e05f803d3b57
          ports:
            - containerPort: 8084
          env:
            - name: "SPRING_DATASOURCE_URL"
              value: "jdbc:postgresql://postgres:5432/financetracker"
            - name: "SPRING_DATASOURCE_USERNAME"
              value: "postgres2"
            - name: "SPRING_DATASOURCE_PASSWORD"
              value: "password"
            - name: "SPRING_JPA_HIBERNATE_DDL_AUTO"
              value: "update"
